name: malware filter
on:
  issue_comment:
    types: [created, edited]
jobs:
  filter:
    runs-on: [ubuntu-latest]
    steps:
     - name: dropbox
       if: contains(github.event.comment.body, 'dropbox.com') # Dropbox URLs
       uses: detomarco/delete-comments@1.1.0
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         repository: typical-developers/oaklands-feedback
         comment-id: ${{github.event.comment.id}}
     - name: mega
       if: contains(github.event.comment.body, 'mega.nz') # Mega URLs
       uses: detomarco/delete-comments@1.1.0
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         repository: typical-developers/oaklands-feedback
         comment-id: ${{github.event.comment.id}}
     - name: mediafire
       if: contains(github.event.comment.body, 'mediafire.com') # Mediafire URLs
       uses: detomarco/delete-comments@1.1.0
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         repository: typical-developers/oaklands-feedback
         comment-id: ${{github.event.comment.id}}
     - name: webhook_post
       run: echo ${{needs}}
       # if: steps.dropbox.conclusion == 
