name: malware filter
on:
  issue_comment:
    types: [created, edited]
jobs:
  job01:
    runs-on: [re-centos7]
    steps:
     - name: dropbox
       if: contains(github.event.comment.body, 'dropbox') # dropbox URLs
       uses: detomarco/delete-comment@v1
       with:
         token: ${GITHUB_TOKEN}
         repository: typical-developers/oaklands-feedback
         comment-id: ${{github.event.comment.id}}
