name: malware filter
on:
  issue_comment:
    types: [created, edited]
jobs:
  filter:
    runs-on: [ubuntu-latest]
    steps:
     - id: dropbox
       name: dropbox
       if: contains(github.event.comment.body, 'dropbox.com') # Dropbox URLs
       uses: detomarco/delete-comments@1.1.0
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         repository: typical-developers/oaklands-feedback
         comment-id: ${{github.event.comment.id}}
     - id: mega
       name: mega
       if: contains(github.event.comment.body, 'mega.nz') # Mega URLs
       uses: detomarco/delete-comments@1.1.0
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         repository: typical-developers/oaklands-feedback
         comment-id: ${{github.event.comment.id}}
     - id: mediafire
       name: mediafire
       if: contains(github.event.comment.body, 'mediafire.com') # Mediafire URLs
       uses: detomarco/delete-comments@1.1.0
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         repository: typical-developers/oaklands-feedback
         comment-id: ${{github.event.comment.id}}
     - name: dump_test
       env:
         STEPS: ${{ toJson(steps) }}
       run: echo "$STEPS"
     - name: webhook_post
       if: steps.dropbox.conclusion == 'skipped' && steps.mega.conclusion == 'skipped' && steps.mediafire.conclusion == 'skipped' # Run only when we skip all other steps
       uses: tsickert/discord-webhook@v5.3.0
       with:
         webhook-url: ${{ secrets.WEBHOOK_URL }}
         embed-title: ${{github.event.issue.title}}
         embed-description: ${{github.event.comment.body}}
         embed-url: ${{github.event.comment.html_url}}
         embed-author-name: ${{github.event.comment.user.login}}
         embed-author-url: ${{github.event.comment.user.html_url}}
         embed-author-icon-url: ${{github.event.comment.user.avatar_url}}
